/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author 0062953
 */
public class FromPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FromPrincipal
     */
    public FromPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadastroPessoa = new javax.swing.JCheckBoxMenuItem();
        MenuCadastroCidade = new javax.swing.JCheckBoxMenuItem();
        MenuSobre = new javax.swing.JMenu();
        MenuSobreOpcoes = new javax.swing.JRadioButtonMenuItem();
        MenuSobreConfiguracao = new javax.swing.JRadioButtonMenuItem();
        MenuSobreAjuda = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maçã");

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        MenuCadastro.setText("Cadastro");

        MenuCadastroPessoa.setSelected(true);
        MenuCadastroPessoa.setText("Pessoa");
        MenuCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroPessoaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroPessoa);
        MenuCadastroPessoa.getAccessibleContext().setAccessibleDescription("");

        MenuCadastroCidade.setSelected(true);
        MenuCadastroCidade.setText("Cidade");
        MenuCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroCidadeActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroCidade);

        MenuPrincipal.add(MenuCadastro);

        MenuSobre.setText("Sobre");

        MenuSobreOpcoes.setSelected(true);
        MenuSobreOpcoes.setText("Opções");
        MenuSobreOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSobreOpcoesActionPerformed(evt);
            }
        });
        MenuSobre.add(MenuSobreOpcoes);

        MenuSobreConfiguracao.setSelected(true);
        MenuSobreConfiguracao.setText("Configurações");
        MenuSobre.add(MenuSobreConfiguracao);

        MenuSobreAjuda.setSelected(true);
        MenuSobreAjuda.setText("Ajuda");
        MenuSobre.add(MenuSobreAjuda);

        MenuPrincipal.add(MenuSobre);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroCidadeActionPerformed
            FromCidade form = new FromCidade(this, true);
            form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
            form.setTitle("Cidade");
            form.setLocationRelativeTo(null);
            form.setResizable(false);
            form.setVisible(true);
    }//GEN-LAST:event_MenuCadastroCidadeActionPerformed

    private void MenuSobreOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSobreOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSobreOpcoesActionPerformed

    private void MenuCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroPessoaActionPerformed
        JOptionPane.showMessageDialog(null, "Estou triste "+"\n"+ "Com raiva");
    }//GEN-LAST:event_MenuCadastroPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JCheckBoxMenuItem MenuCadastroCidade;
    private javax.swing.JCheckBoxMenuItem MenuCadastroPessoa;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JRadioButtonMenuItem MenuSobreAjuda;
    private javax.swing.JRadioButtonMenuItem MenuSobreConfiguracao;
    private javax.swing.JRadioButtonMenuItem MenuSobreOpcoes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
